include themes/rose-pine-moon.conf

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        15.0

text_composition_strategy platform

modify_font cell_height 115%
modify_font underline_position 2px

hide_window_decorations titlebar-only
macos_titlebar_color background
macos_show_window_title_in window

window_padding_width 10 8
placement_strategy center

resize_in_steps yes

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2

copy_on_select clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary

map cmd+r load_config_file

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

allow_remote_control yes
listen_on unix:/tmp/mykitty
